version: '3'

services:
  mongodb:
    image: mongo:latest
  backend:
    image: localhost:5000/technicaltestback
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  frontend:
    image: localhost:5000/technicaltestfront
    command: node index.js
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 30s
    ports:
      - "3000:3000"
    depends_on:
      - backend
