---
# tasks file for docker services
- name: copy compose in place
  copy:
    src: docker-compose.yml
    dest: /usr/code/

- name: stack deploy
  command: docker stack deploy --compose-file=/usr/code/docker-compose.yml Foxy
