---
# tasks file for docker registry / backend image

- name: Create repo for code backend if not already present
  file:
    path: /usr/code/backend
    state: directory
    recurse: yes
    mode: 5755

- name: copy code in place
  copy:
    src: backend/
    dest: /usr/code/backend/

- name: copy backend Dockerfile in place
  template:
    src: Backend.j2
    dest: /usr/code/backend/Dockerfile

- name: build backend in order to get image
  command: docker build .
  args:
    chdir: /usr/code/backend

- name: get image ID
  command: docker images
  register: backEndImg

- name: debug image ID
  debug:
    msg: "backend image ID : {{ backEndImg.stdout_lines[1].split()[2] }}"

- name: tag backend image
  command: docker tag "{{ backEndImg.stdout_lines[1].split()[2] }}" localhost:5000/technicaltestback

- name: push backend image
  command: docker push localhost:5000/technicaltestback
