---
# tasks file for docker role

- name: install the prerequisites package
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: install docker
  command: yum install -y docker

- name: start/enable Docker
  service:
    name: docker
    enabled: true
    state: started

- name: Add the user to the group of 'docker'
  user:
    name: ec2-user
    comment: user
    group: docker
    append: true

- name: restart docker service
  service:
    name: docker
    state: started

- name: verify if docker is installed
  command: docker info
  register: docker_info
  changed_when: false
