# Install docker on each machine
- hosts: all
  become: true
  roles:
    - docker
  #become: yes

# Create a Highly Available Docker Swarm cluster
- hosts: manager
  become: true
  roles:
    - swarm_manager

# Join the Docker Swarm cluster for the workers
- hosts: workers
  become: true
  roles:
    - swarm_workers

# Deploy the provided application into the cluster
- hosts: manager
  become: true
  roles:
    - docker_registry
    - docker_services

